// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  defaultSidebar: [{type: 'autogenerated', dirName: '.', collapsed: true,},],

  learnSidebar: [{ type: "autogenerated", dirName: "learn" }],
  buildSidebar: [{ type: "autogenerated", dirName: "build" }],
  quickstartSidebar: [{ type: "autogenerated", dirName: "quickstart" }],
};

module.exports = sidebars;
