// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  defaultSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
      collapsed: true, // 👈 ensures top-level collapsibles start closed
    },
  ],
  learnSidebar: [
    {
      type: 'autogenerated',
      dirName: 'learn',
      collapsed: true,
    },
  ],
  buildSidebar: [
    {
      type: 'autogenerated',
      dirName: 'build',
      collapsed: true,
    },
  ],
  quickstartSidebar: [
    {
      type: 'autogenerated',
      dirName: 'quickstart',
      collapsed: true,
    },
  ],
};

module.exports = sidebars;
