// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  learnSidebar: [{ type: "autogenerated", dirName: "learn" }],
  buildSidebar: [{ type: "autogenerated", dirName: "build" }],
};

module.exports = sidebars;
